describe('template spec', () => {
  it('passes', () => {
    cy.visit('https://front.serverest.dev/login')
    cy.get('[data-testid="email"]').type('lume@teste.com.br')
    cy.get('[data-testid="senha"]').type('teste')
    cy.get('[data-testid="entrar"]').click()
    cy.wait(1000)
    cy.cadastroProduto('Skate11111', 1.0, 'Skate', 100)
    cy.get('[data-testid="listar-produtos"]').click()
    cy.get('tr')
      .children('td')
      .contains('Skate')
      .next()
      .next()
      .next()
      .next()
      .next()
      .children('div')
      .children('.btn-danger')
      .click()
  })
})